services:
  postgres-catalog:
    image: postgres:16-alpine
    container_name: postgres-catalog
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
    ports:
      - "5432:5432"

  postgres-booking:
    image: postgres:16-alpine
    container_name: postgres-booking
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
    ports:
      - "5433:5432"